### ISSUE TITLE
No Input Validation for `/permission` Command

### ISSUE THREAD

**Issue by amnotbananaama** [yitzy299/server-simplified#2]
The `/permission` command doesn't validate that user input matches an actual permission used by the mod, or even whether the permission exists or not. This manifests in 3 ways: 

**1. You can give players the same permission more than once:**  
---
`/permission add <username> mute`
-> "Added permission mute to \<username\>"
`/permission add <username> mute`
-> :x: "Added permission mute to \<username\>"
-> **Expected behavior**: "\<username\> already has that permission!"
  
**2. You can give players non-existent permissions:**
---
`/permission add <username> foo`
-> :x: "Added permission foo to \<username\>"
-> **Expected behavior**: At the very least fail, ideally return a meaningful error like "No such permission foo!"
  
**3. You can remove permissions that players don't have**  
---
`/permission remove <username> staffchat`
-> :x: "An unexpected error occurred trying to execute that command"
-> **Expected behavior:** "Player \<username\> doesn't have the permission staffchat!"
`/permission <username> remove foo`
-> :x: "An unexpected error occurred trying to execute that command"
-> **Expected behavior**: At the very least fail, ideally return a meaningful error like "No such permission foo!"  
  
---
Permissions show up weirdly in chat as well, possibly related to #1. I'm not even sure if they actually work because of this, all commands were performed as OP. 

![image](https://user-images.githubusercontent.com/6319658/100526004-178cf780-3193-11eb-83de-ad56fcc20943.png)

**Comment by yitzy299** [comment]
Same issue as #1, fixing now

**Comment by amnotbananaama** [comment]
Thanks!

**Comment by yitzy299** [comment]
Fixed in the latest commit
