### ISSUE TITLE
Add command Alisis 

### ISSUE THREAD

**Issue by ElijahRus250** [yitzy299/server-simplified#4]
For vanilla commands like /teammsg can you make an easy way to make a command like /t to do the same thing

**Comment by yitzy299** [comment]
I will have a look, might even be a seperate mod

**Comment by amnotbananaama** [comment]
A really robust and well-done mod for this [already exists](https://github.com/FlashyReese/CommandAliases), called CommandAliases. It's really powerful and you can create an alias like that (and more).
