### ISSUE TITLE
Add Nicks

### ISSUE THREAD

**Issue by nullpanda** [yitzy299/server-simplified#6]
Please add /nick, default usable by anyone, config option to prefix names in chat with a customizable character to indicate it's a nick, config option to display real name in tab list in parentheses after the nick.

**Comment by dillonbarnes** [comment]
I like the idea but would prefer it if it was only for people with permission.
Then server admins can control who can use it.

**Comment by yitzy299** [comment]
There are other mods that provide this, I think I'll close
