### ISSUE TITLE
Staffchat with Player with a teams

### ISSUE THREAD

**Issue by JRCLARK25** [yitzy299/server-simplified#8]
One issue I have discovered. Staffchat does not show username if that player has a Minecraft team assigned to them.
It just shows message as [SC] <> Test 
Is this fixable through a config? 
![Staffchat Team](https://user-images.githubusercontent.com/70182392/106106390-12084b00-610b-11eb-8529-906c1933647b.png)

**Comment by yitzy299** [comment]
That's really strange: I'll take a look

**Comment by yitzy299** [comment]
Would you be able to check if there are any errors in the logs?

**Comment by JRCLARK25** [comment]
This is all that appears in  the server log 
First 3 are from when I sent a message
Next 3 are from a mod sending 1 message

02.02 01:16:03 [Server] Netty Epoll Server IO #16/INFO [SC] 
02.02 01:16:03 [Server] Netty Epoll Server IO #16/INFO [SC] 
02.02 01:16:03 [Server] Netty Epoll Server IO #16/INFO [SC] 
02.02 01:16:12 [Server] Server thread/INFO [SC] 
02.02 01:16:12 [Server] Server thread/INFO [SC] 
02.02 01:16:12 [Server] Server thread/INFO [SC]

**Comment by JRCLARK25** [comment]
My message I moved into staffchat then typed a message "/staffchat" then "test"
The other message was a mod typing "/staffchat Test"

**Comment by yitzy299** [comment]
I'm gonna take a look now

**Comment by yitzy299** [comment]
Really odd, might be a vanilla bug, but it's fixed anyway
